Apply fix to mono Saffire mixer as suggested by John Vaites.  Logically this seems like the correct thing to do but as I don't have a Saffire I can't test this myself.  If this breaks other interfaces please revert and apply something more appropriate.  The error this fixes in John's case is "AttributeError: 'SaffireMixerMono' object has no attribute 'sldIN1Out910'".
git-svn-id: http://subversion.ffado.org/ffado/trunk@2018 2be59082-3212-0410-8809-b0798e1608f0